apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bala
  name: bala
spec:
  containers:
  - image: nginx
    name: bala
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
