apiVersion: apps/v1
kind: ReplicaSet
metadata:
  creationTimestamp: null
  labels:
    app: tracedata
    type: backend
  name: nginx-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tracedata
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tracedata
        type: backend
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
